version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.1"

before_build:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install hererocks
  - pip install codecov
  - hererocks here --%LUA% -r latest
  - call here\bin\activate
  - luarocks install busted
  - luarocks install cluacov
  - luarocks install luautf8
  - luarocks install luasocket

build_script:
  - luarocks make

test_script:
  - busted -c
  - luacheck .
  - luacheck .

after_test:
  - luacov
  - codecov -f luacov.report.out -X gcov
